"""
GraphQL type definitions for the OHDSI Community Intelligence Platform.

All Strawberry types are organized by domain and re-exported here
for convenient imports.
"""
from .content import (
    Author,
    ContentMetrics,
    Content,
    SearchResult,
)
from .review import (
    ClassificationFactor,
    ReviewItem,
    QueueStats,
)
from .user import (
    User,
    AuthPayload,
)
from .dashboard import (
    CategoryStat,
    AuthorStat,
    CollaborationMetrics,
    FundingMetrics,
    YearRange,
    MonthlyTrend,
    DashboardStats,
    TimelinePoint,
    TimelineStats,
    NetworkNode,
    NetworkLink,
    NetworkStats,
    JournalStat,
    ArticleStat,
    VideoStat,
    ChannelStat,
    RepoStat,
    LanguageStat,
    TopicStat,
    DocStat,
    DocTypeStat,
    PubMedMetrics,
    YouTubeMetrics,
    GitHubMetrics,
    DiscourseMetrics,
    WikiMetrics,
    SourceMetrics,
    TrendingTopic,
    TrendingSearch,
    TrendingContent,
    TrendingData,
    EngagementMetrics,
    QualityDistribution,
    ActivityItem,
    ContentGrowth,
    DashboardData,
)
from .citation import (
    CitationNode,
    CitationEdge,
    CitationMetrics,
    CitationNetwork,
    CitationStats,
    CitationTimelineEntry,
    CitationTimeline,
    CitationMilestone,
    CitationMilestones,
    CitationCluster,
    CitationClusters,
)
from .landscape import (
    Position,
    TerritoryLabel,
    Territory,
    SemanticGap,
    TerrainData,
    SemanticContext,
    PaperPosition,
    LandscapeStats,
    Landscape,
)
from .prediction import (
    PredictionFactor,
    PredictionResult,
    ArticleData,
    PubMedPrediction,
    ModelStats,
)

__all__ = [
    # Content
    "Author",
    "ContentMetrics",
    "Content",
    "SearchResult",
    # Review
    "ClassificationFactor",
    "ReviewItem",
    "QueueStats",
    # User
    "User",
    "AuthPayload",
    # Dashboard
    "CategoryStat",
    "AuthorStat",
    "CollaborationMetrics",
    "FundingMetrics",
    "YearRange",
    "MonthlyTrend",
    "DashboardStats",
    "TimelinePoint",
    "TimelineStats",
    "NetworkNode",
    "NetworkLink",
    "NetworkStats",
    "JournalStat",
    "ArticleStat",
    "VideoStat",
    "ChannelStat",
    "RepoStat",
    "LanguageStat",
    "TopicStat",
    "DocStat",
    "DocTypeStat",
    "PubMedMetrics",
    "YouTubeMetrics",
    "GitHubMetrics",
    "DiscourseMetrics",
    "WikiMetrics",
    "SourceMetrics",
    "TrendingTopic",
    "TrendingSearch",
    "TrendingContent",
    "TrendingData",
    "EngagementMetrics",
    "QualityDistribution",
    "ActivityItem",
    "ContentGrowth",
    "DashboardData",
    # Citation
    "CitationNode",
    "CitationEdge",
    "CitationMetrics",
    "CitationNetwork",
    "CitationStats",
    "CitationTimelineEntry",
    "CitationTimeline",
    "CitationMilestone",
    "CitationMilestones",
    "CitationCluster",
    "CitationClusters",
    # Landscape
    "Position",
    "TerritoryLabel",
    "Territory",
    "SemanticGap",
    "TerrainData",
    "SemanticContext",
    "PaperPosition",
    "LandscapeStats",
    "Landscape",
    # Prediction
    "PredictionFactor",
    "PredictionResult",
    "ArticleData",
    "PubMedPrediction",
    "ModelStats",
]
