DROP TABLE IF EXISTS beta;
DROP TABLE IF EXISTS pubmed_ignore;
DROP TABLE IF EXISTS dashboard;

CREATE TABLE beta (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  json JSON NOT NULL
);

CREATE TABLE pubmed_ignore (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  json JSON NOT NULL
);

CREATE TABLE dashboard (
  id TEXT PRIMARY KEY,
  json JSON NOT NULL
)
