import { EXAMPLE_SITE } from "navigation";
import { Study } from "./studies.service";

export const EXAMPLE_STUDIES: Study[] = [
  {
    id: 1,
    siteId: EXAMPLE_SITE.id,
    title: 'Reproducibility_Ray JAMA2021', 
    pinned: true,
    gitRepo: 'ohdsi-studies/ReproducibilityRayJAMA2021',
    status: 'started',
    useCases: ['Population Level Estimation'],
    type: 'Clinical Application',
    tags: [ 'Reproducibility', 'DOACs'],
    lead: 'Asieh Golozar',
    draft: 'Apr. 1, \'22',
    start: 'Apr. 1, \'22',
    end: null,
    protocol: 'https://github.com/ohdsi-studies/ReproducibilityRayJAMA2021/tree/master/documents/DOACs.REPLICATION_Protocol_DRAFT_April.2022.docx',
    publications: null,
    results: 'https://example.com',
    description: "Recently, a high-quality observational comparative cohort study conducted using a nation-wide sample of U.S. administrative claims was recently published in JAMA demonstrating a significantly increased risk of major ischemic or hemorrhagic events associated with treatment with rivaroxaban compared with apixaban. This study aims to independently replicate the original study according to its description in the recent publication and supplemental materials, using a similar database as was used in the original study. Additionally, we plan to evaluate the robustness of the study findings by conducting sensitivity analyses, assessing: 1) changes to definitions of exposure and outcome phenotypes, 2) calibration of effect estimates using empirical null distributions, and 3) observable study diagnostics that inform the validity of a given analysis. Finally, we plan to explore the generalizability of the findings by executing the analysis on several study databases that vary with respect to the populations they include (e.g. U.S. and non-U.S.) and their mechanisms of data capture (e.g. administrative claims, electronic health records data)."
  },
  {
    id: 2,
    siteId: EXAMPLE_SITE.id,
    title: 'PORPOISE: Development and External Validation of ML Models for Identifying Patients at Risk of Postoperative Prolonged Opioid Use', 
    pinned: true,
    gitRepo: 'ohdsi-studies/PORPOISE',
    status: 'started',
    useCases: [],
    type: '',
    tags: [],
    lead: '',
    draft: 'Apr. 1, \'22',
    start: 'Apr. 1, \'22',
    end: null,
    protocol: null,
    publications: null,
    results: null,
    description: "The PORPOISE study develops and validates machine learning (ML) models to predict patients at risk of prolonged opioid use in a diverse, multisite cohort by evaluating not only their performance but also their generalizability, discrimination, and calibration abilities over different subgroups, including diabetes, depression, and obesity."
  },
  {
    id: 3,
    siteId: EXAMPLE_SITE.id,
    title: 'Relative Risk of Cervical Neoplasms Associated with Copper and Levonorgestrel Secreting Intrauterine Devices: Real World Evidence from the OHDSI Network', 
    pinned: false,
    gitRepo: 'ohdsi-studies/IUDEHREstimationStudy',
    status: 'finalized',
    useCases: ['Characterization', 'Population Level Estimation'],
    type: 'Clinical Application',
    tags: [ 'iud'],
    lead: 'Matthew Spotnitz',
    draft: 'Sep. 23, \'19',
    start: 'Sep. 23, \'19',
    end: null,
    protocol: 'https://github.com/ohdsi-studies/IUDEHREstimationStudy/blob/master/documents/IUD%20Cervical%20Neoplasms%20Estimation%20Protocol.docx',
    publications: null,
    results: null,
    description: "This study extends the prior single-site study to the OHDSI network."
  },
  {
    id: 4,
    siteId: EXAMPLE_SITE.id,
    title: 'Large-scale Evidence Generation and Evaluation across a Network of Databases for Type 2 Diabetes Mellitus (LEGEND-T2DM)', 
    pinned: false,
    gitRepo: 'ohdsi-studies/LegendT2dm',
    status: 'results available',
    useCases: ['Population Level Estimation'],
    type: 'Clinical Application',
    tags: [],
    lead: 'Marc A. Suchard',
    draft: 'Nov. 1, \'21',
    start: 'Nov. 1, \'21',
    end: null,
    protocol: 'https://ohdsi-studies.github.io/LegendT2dm/Protocol.html',
    publications: null,
    results: null,
    description: "This study extends the prior single-site study to the OHDSI network."
  },
  {
    id: 5,
    siteId: EXAMPLE_SITE.id,
    title: 'HIVTreatmentPathways', 
    pinned: false,
    gitRepo: 'ohdsi-studies/HIVTreatmentPathways',
    status: 'repo created',
    useCases: [],
    type: null,
    tags: [],
    lead: 'Marc A. Suchard',
    draft: 'Nov. 1, \'21',
    start: null,
    end: null,
    protocol: null,
    publications: null,
    results: null,
    description: ""
  },
  {
    id: 6,
    siteId: EXAMPLE_SITE.id,
    title: 'Assessing Health Equity in Mental Healthcare Delivery Using a Federated Network Research Model', 
    pinned: false,
    gitRepo: 'ohdsi-studies/MentalHealthEquity',
    status: 'started',
    useCases: ['Characterization', 'Population Level Estimation'],
    type: 'Methods Research',
    tags: ['Mental Health', 'Equity', 'Depression', 'Bipolar Disorder', 'Suicide', 'Characterization'],
    lead: 'Jacob S. Zelko',
    draft: 'Sep. 16, \'21',
    start: 'Sep. 16, \'21',
    end: null,
    protocol: null,
    publications: null,
    results: null,
    description: "For this effort, we conduct a federated network research study utilizing claims and EHR data alongside existing survey data. Through this analysis, we will develop clinical phenotypes around mental health conditions and build analytics packages to uncover unknown relationships between claims, EHR, and survey data. This effort could lead health officials to implement better informed interventions that will increase equitable access to mental healthcare across vulnerable populations, supports efforts to decrease acute mental health-related morbidities, and improve the efficacy of health spending."
  },
  {
    id: 7,
    siteId: EXAMPLE_SITE.id,
    title: 'EXAMPLE: Draft example', 
    pinned: false,
    gitRepo: null,
    status: 'draft',
    useCases: [],
    type: null,
    tags: [],
    lead: 'Nate',
    draft: 'Apr. 1, \'22',
    start: null,
    end: null,
    protocol: null,
    publications: null,
    results: null,
    description: "The PORPOISE study develops and validates machine learning (ML) models to predict patients at risk of prolonged opioid use in a diverse, multisite cohort by evaluating not only their performance but also their generalizability, discrimination, and calibration abilities over different subgroups, including diabetes, depression, and obesity."
  },
]