# Requires these secrets:
# GH_TOKEN - requires write permissions to ghcr
# IMAGE_NAME - assumes ghcr.io prefix

name: 'cicd'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v1
        with:
          use: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and release devcontainer Multi-Platform
        uses: devcontainers/ci@v0.2
        with:
          imageName: ${{ secrets.IMAGE_NAME }}
          cacheFrom: ${{ secrets.IMAGE_NAME }}
          eventFilterForPush: |
            push
            workflow_dispatch
          subFolder: projects/development
          platform: linux/amd64,linux/arm64
    
  test:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: npm run test:ci
        uses: devcontainers/ci@v0.2
        with:
          cacheFrom: ${{ secrets.IMAGE_NAME }}
          runCmd: yarn test:ci